config/routes.rb
FizzBuzz::Application.routes.draw do
  get 'fizz' => 'fizz_buzz#fizz'
  get 'buzz' => 'fizz_buzz#buzz'
  get 'fizz_buzz' => 'fizz_buzz#fizz_buzz'
  get 'fail' => 'fizz_buzz#fail'
  post 'answer' => 'fizz_buzz#answer'

  root to: 'fizz_buzz#index'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/fizz_buzz_controller.rb
class FizzBuzzController < ApplicationController
  def fizz
    @message = "Fizz."
  end

  def buzz
    @message = "Buzz."
  end

  def fizz_buzz
    @message = "Fizz Buzz."
  end

  def fail
    @message = params[:number].strip.to_i.to_s
  end

  def index
  end

  def answer
    number = params[:number].strip.to_i

    if number % 5 == 0 && number % 3 == 0
      redirect_to fizz_buzz_url
    elsif number % 5 == 0
      redirect_to fizz_url
    elsif number % 3 == 0
      redirect_to buzz_url
    else
      redirect_to fail_url(number: number)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/fizz_buzz/buzz.html.erb
<div class="container buzz">
  <%= render 'shared/number_form' %>
</div>

app/views/fizz_buzz/fail.html.erb
<div class="container fail">
  <%= render 'shared/number_form' %>
</div>

app/views/fizz_buzz/fizz.html.erb
<div class="container fizz">
  <%= render 'shared/number_form' %>
</div>

app/views/fizz_buzz/fizz_buzz.html.erb
<div class="container fizz-buzz">
  <%= render 'shared/number_form' %>
</div>

app/views/fizz_buzz/index.html.erb
<div class="container index">
  <%= render 'shared/number_form' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FizzBuzz</title>
  <link href="http://fonts.googleapis.com/css?family=Istok+Web:400,700" rel="stylesheet" type="text/css">
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>
<%= yield :javascript %>
</body>
</html>

app/views/shared/_number_form.html.erb
<div class="form">
  <h1><%= @message || "&nbsp;".html_safe %></h1>

  <form action="<%= answer_url %>" method="POST">
    <input type="text" name="number" class="number" placeholder="Enter a Number"/>
  </form>
</div>

<%- content_for(:javascript) do %>
  <script type="text/javascript">
    var timer = null;

    function doProcessInput(input) {
        var val = $(input).val();

        if(val.match(/^\s*\d+\s*$/)) {
            $(input).parents('form').submit();
        } else if(val.match(/^\s*$/)) {
          // Don't do anything.
        } else {
            var $div = $('<div/>').text("That's not a number!");
            $(input).after($div);
        }
    }

    $('input.number').on('keydown', function() {
        // this is a little wasteful...should only do it if need be!
        $(this).siblings('div').remove();

        if(timer) {
          window.clearTimeout(timer);
        }

        // Save this for later.
        var _this = this;

        timer = window.setTimeout(function() {
          doProcessInput(_this);
        }, 500);
    });

    $('input.number').on('change', function() {
        doProcessInput(this);
    });

    $('input.number').focus();
  </script>
<%- end %>